import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import './style.css';
const $=id=>document.getElementById(id), host=$('viewport');
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;host.append(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.01,100);
const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();const env=pmrem.fromScene(room,.04);scene.environment=env.texture;room.dispose();pmrem.dispose();
scene.add(new THREE.HemisphereLight(0xd8e8ff,0x3b4230,2));const key=new THREE.DirectionalLight(0xffe7c4,3);key.position.set(2,3,2);scene.add(key);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.15;controls.maxDistance=10;
const grid=new THREE.GridHelper(8,40,0x49574a,0x2b382f);grid.material.transparent=true;grid.material.opacity=.3;scene.add(grid);
const loader=new GLTFLoader(),cache=new Map();let assets=[],current=null,model=null,mode='inspect',detached=false,token=0;
function frame(){if(!model)return;mode='inspect';camera.fov=38;camera.updateProjectionMatrix();controls.enabled=true;$('orbit').setAttribute('aria-pressed','true');$('fps').setAttribute('aria-pressed','false');$('crosshair').hidden=true;document.querySelector('.stage-note').textContent='DRAG TO ORBIT · SCROLL TO ZOOM';model.position.set(0,0,0);model.rotation.set(0,0,0);const bounds=new THREE.Box3().setFromObject(model),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());const d=Math.max(...size.toArray())*(current.category==='Weapon'?1.05:1.65);controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(d,d*.40,-d*.65));camera.lookAt(center);controls.update();grid.position.y=bounds.min.y-.035;grid.visible=true;}
async function select(asset){const request=++token;$('loading').hidden=false;$('loading').textContent='Loading asset…';try{if(!cache.has(asset.id))cache.set(asset.id,await loader.loadAsync(asset.file));if(request!==token)return;if(model)scene.remove(model);model=cache.get(asset.id).scene;current=asset;scene.add(model);detached=false;const mag=model.getObjectByName(asset.id+'__magazine');if(mag)mag.position.y=0;$('magazine').textContent='Detach magazine';$('magazine').disabled=asset.category!=='Weapon';$('fps').disabled=asset.category!=='Weapon';$('title').textContent=asset.title;$('description').textContent=asset.description;$('triangles').textContent=asset.triangles.toLocaleString();$('size').textContent=(asset.bytes/1024).toFixed(0)+' KB';$('dimensions').textContent=asset.dimensions.map(n=>n.toFixed(2)).join(' × ');$('category').textContent=asset.category.toUpperCase()+' / '+String(assets.indexOf(asset)+1).padStart(2,'0');$('asset-number').textContent=String(assets.indexOf(asset)+1).padStart(2,'0');$('download').href=asset.file;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.id===asset.id));applyWire();frame();$('loading').hidden=true;}catch(error){$('loading').textContent='Could not load asset: '+error.message;console.error(error);}}
function applyWire(){model?.traverse(o=>{if(o.isMesh){const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.wireframe=$('wire').checked);}});}
$('wire').onchange=applyWire;$('reset').onclick=frame;$('orbit').onclick=frame;
$('fps').onclick=()=>{if(!model||current.category!=='Weapon')return;mode='fps';camera.fov=65;camera.updateProjectionMatrix();model.rotation.set(0,0,0);model.position.set(.17,-.235,-.34);controls.enabled=false;camera.position.set(0,0,0);camera.lookAt(0,0,-1);grid.visible=false;$('orbit').setAttribute('aria-pressed','false');$('fps').setAttribute('aria-pressed','true');$('crosshair').hidden=false;document.querySelector('.stage-note').textContent='VIEWMODEL SCALE CHECK · NO HAND RIG';};
$('magazine').onclick=()=>{const mag=model?.getObjectByName(current.id+'__magazine');if(!mag)return;detached=!detached;mag.position.y=detached?-.16:0;$('magazine').textContent=detached?'Attach magazine':'Detach magazine';};
new ResizeObserver(()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();}).observe(host);
renderer.setAnimationLoop(()=>{controls.autoRotate=$('rotate').checked&&mode==='inspect';if(controls.enabled)controls.update();renderer.render(scene,camera);});
try{const response=await fetch('/models/manifest.json');if(!response.ok)throw new Error('Manifest unavailable');assets=await response.json();assets.forEach((a,i)=>{const b=document.createElement('button');b.dataset.id=a.id;b.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span>${a.title}`;b.onclick=()=>select(a);$('assets').append(b);});await select(assets[0]);}catch(error){$('loading').textContent=error.message;console.error(error);}
